name: Deploy - Staging

on:
  push:
    branches:
      - staging
      - 'feat-*'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: staging
      s3-prefix: /${{ github.ref_name }}
      invalidation-paths: /${{ github.ref_name }}/*
      deploy-url: https://${{ github.ref_name }}.staging.dwightgunning.com
    secrets: inherit
