name: Deploy - Production

on:
  push:
    branches:
      - production

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: production
      invalidation-paths: /*
      deploy-url: https://www.dwightgunning.com
    secrets: inherit
