name: Build And Push Osmium Docker Image

on: [ workflow_dispatch ]

jobs:
  build-and-push-image:
    name: Build and Push Image
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        repository: dwightgunning/dwightgunning.com
        path: dwightgunning.com

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: dwightgunning.com/tiles/osmium-tool
        platforms: linux/amd64,linux/arm64/v8
        push: true
        tags: ghcr.io/${{ github.repository }}/osmium-tool:latest
