name: Build And Push Tippecanoe Docker Image

on: [ workflow_dispatch ]

jobs:
  build-and-push-image:
    name: Build and Push Image
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Tippecanoe repo
      uses: actions/checkout@v3
      with:
        repository: dwightgunning/tippecanoe
        path: tippecanoe

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: tippecanoe
        push: true
        tags: ghcr.io/${{ github.repository }}/tippecanoe:latest
